### PR TITLE
fix auto indentation

### LINKED ISSUE #1: Respect indentation
``` js
function() {
    var top = _.identity(oquery.$top);
}
```
1. Select `var top = _.identity(oquery.$top);`
2. Ctrl+Shift+Q

``` js
function() {
    var top = _.identity(oquery.$top);
 console.log("    var top = _.identity(oquery.$top); ",     var top = _.identity(oquery.$top););
}
```

console.log is pasted to the beginning of line plus 1 space
Expecting:

`````` js
```js
function() {
    var top = _.identity(oquery.$top);
    console.log("    var top = _.identity(oquery.$top); ",     var top = _.identity(oquery.$top););
}
``````

### PR DESCRIPTION
**Pull request by JuoCode**
fix #1

### CODE REVIEW

**Comment by fabiodamasceno** [comment]
Thx for the contribution Juo, can you update unit tests?

Hugs,

**Comment by fabiodamasceno** [comment]
Thanks a lot @JuoCode people like you makes things happen!
Congrats!

**Comment by JuoCode** [comment]
😄

**Comment by JuoCode** [comment]
Could you publish this fix to Marketplace? Thanks.

**Pull request merged**
